name: workflow-unit-molnet

on: [push]

jobs:
  test-molnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        miniconda-version: 'latest'
        python-version: 3.7
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        apt-get purge locales
        apt-get install locales-all
        conda install -c conda-forge nose2
        pip install -r requirements.txt
        wget https://data.qiime2.org/distro/core/qiime2-2019.7-py36-linux-conda.yml
        conda env create -n qiime2-2019.7 --file qiime2-2019.7-py36-linux-conda.yml  --force
        rm qiime2-2019.7-py36-linux-conda.yml
    - name: Test with nose2
      shell: bash -l {0}
      run: |
        conda init bash
        conda env list
        cd molnetenhancer/test && nose2 -v
